### ISSUE TITLE
草料二维码识别不支持支付宝了 换个二维码识别接口吧

### ISSUE THREAD

**Issue by 504750975** [szvone/vmqphp#12]
如题

**Comment by szvone** [comment]
没有找到其他接口，如果你有接口 再提交issues吧

**Comment by 504750975** [comment]
所以为什么不是PHP的二维码识别扩展呢？
官网:http://phpqrcode.sourceforge.net/
下载源码：https://github.com/endroid/qr-code
虽然有的时候识别会出现稍微错误，但是还是比较有用的。
