### ISSUE TITLE
回调参数的同步跳转和异步回调的优先级不对

### ISSUE THREAD

**Issue by canyiad** [szvone/vmqphp#13]
应该是同步跳转的优先级最高,然后才是异步回调.不然异步出错,同步是正确的,后台会出现2个相同金额的订单,一个是无订单转账状态,一个是通知失败状态

**Comment by szvone** [comment]
表示没听懂你在说啥

**Comment by canyiad** [comment]
帝国cms不支持异步回调
使用v支付后
支付平台优先判断异步回调结果，然后就是支付不成功
但是同时同步跳转又正常，然后平台就会建立一个新的支付订单，属于没匹配的类型
改善:优先判断同步跳转或者后台可以关闭异步回调

Ryan

________________________________

**Comment by szvone** [comment]
所有支付程序含支付宝微信在内，均有同步和异步两种，如果你不想使用异步回调，你可以把application\index\controller\Index.php的492行$re = $this->getCurl($url);修改为$re = "success";
