### ISSUE TITLE
【小白疑问，求教四方】本地服务测试，监控端扫码后，后台还是：监控端未绑定，请您扫码绑定

### ISSUE THREAD

**Issue by zkbqhuang** [szvone/vmqphp#26]
配置数据 localhost/7a151a343a8d8b84a761c8af9262839b

后台服务运行，监控端扫描后，localhost/7a151a343a8d8b84a761c8af9262839b
后台提示：监控端未绑定，请您扫码绑定
查询局域网ip，改成手动配置，192.168.0.101/7a151a343a8d8b84a761c8af9262839b
后台依然是：监控端未绑定，请您扫码绑定

还是说一定要将后台服务放公网上才有效？本地测试不能绑定吗？

**Comment by zkbqhuang** [comment]
监控端点击【检测心跳】，提示：心跳状态错误，请检查配置是否正确
刷新后台    【最后心跳】：无

**Comment by YoK1ng** [comment]
APP也要改

**Comment by zkbqhuang** [comment]
> APP也要改

APP是指Android 源码也要改？apk不是直接下载就能用吗？至少能连接上服务器，现在我这问题是扫码绑定都绑定不上，还不谈支付后面的事，看了其他issue，支付宝和微信版本升级，才会改动Android源码，重新打包，大佬能麻烦说稍微详细一点吗？
